### ISSUE TITLE
Permit users to specify which fields are significant for hash and equality

### ISSUE THREAD

**Issue by gafter** [JuliaServices/AutoHashEqualsCached.jl#27]
We have a number of comments in our code of the form

```julia
# TODO(NHD): @auto_hash_equals (currently can't b/c of existing hash that <something>)
```

If the user could specify which fields are significant, the hash and equality could be automatic.  Perhaps something like this:

```julia
@auto_hash_equals (:name, :node_id) mutable struct Var <: Term
    name :: Id
    annos :: Annos
    node_id :: NodeId
end
```

/cc @NHDaly

**Comment by NHDaly** [comment]
cool! :) Thanks neal, sounds like a nice improvement.

**Comment by gafter** [comment]
This is now done.

`@auto_hash_equals fields=(x, y) struct Point ... end`

or, if you want the hash value cached,

`@auto_hash_equals cache=true fields=(x, y) struct Point ... end`
