### ISSUE TITLE
Package can no longer be installed without having Rematch2 installed

### ISSUE THREAD

**Issue by ORBAT** [JuliaServices/AutoHashEqualsCached.jl#29]
Trying to install or update AutoHashEqualsCached without having Rematch2 installed results in this (with Julia 1.9.1):

```
(jl_BktYPr) pkg> add https://github.com/JuliaServices/AutoHashEqualsCached.jl
    Updating git-repo `https://github.com/JuliaServices/AutoHashEqualsCached.jl`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Rematch2 [351a7294]:
 Rematch2 [351a7294] log:
 ├─Rematch2 [351a7294] has no known versions!
 └─restricted to versions * by AutoHashEqualsCached [887ad303] — no versions left
   └─AutoHashEqualsCached [887ad303] log:
     ├─possible versions are: 0.2.1 or uninstalled
     └─AutoHashEqualsCached [887ad303] is fixed to version 0.2.1
```

**Comment by gafter** [comment]
Yes, I know, this is inconvenient.

The dependency on `Rematch2` is temporary until `Rematch2` is registered (as a new version of `Match`).  There is no other way to represent a test dependency on an unregistered package.

I intend to resolve this issue before registering this package (as a new version of `Match`).

**Comment by gafter** [comment]
I've updated this package to no longer depend on `Rematch.jl`.  I'm also working on moving the functionality of this package to `AutoHashEquals.jl`.
