### ISSUE TITLE
See StructEquality.jl for ideas on generating code

### ISSUE THREAD

**Issue by gafter** [JuliaServices/AutoHashEqualsCached.jl#30]
The package [`StructEquality.jl`](https://github.com/jolin-io/StructEquality.jl) uses `@generated` functions to simplify its implementation.  We should consider that.

**Comment by NHDaly** [comment]
🤔 interesting. So far, i think i prefer what you have in this package to that.

For a bunch of disappointing reasons, we know that generated functions come with a whole host of issues, and i'd prefer to avoid them if it's possible. One day, it would be great to go and fix the generated functions mechanism in julia, remove the perf issues and the world age restrictions, but until then i think they're a last-resort type tool.

**Comment by gafter** [comment]
Oh, right, the generated function would not call recent most specific overloads of `isequal` and `hash` in its implementation, which means it wouldn't do the right thing.

**Comment by NHDaly** [comment]
I think it's not quite that bad.
The code _generated by_ a generated function operates at the normal world age, so it could call the latest isequal and hash.

It's just that the code _during generation_ runs at a fixed world-age. Hope that's clear?

But yeah, nonetheless, it still has perf issues that makes it less desirable than what you currently have i think.

**Comment by NHDaly** [comment]
Could be worth investigating and benchmarking i guess, if you think there are good benefits to be had.

**Comment by gafter** [comment]
It wouldn't work for exactly the reason we abandoned that approach elsewhere: the user needs to be able to specify which fields are significant for hashing and equality.  Overriding a method to produce that symbol list wouldn't work because of world age issues.  Generating code from the macro is a good way to do that.
