### ISSUE TITLE
Add a keyword macro arguments for triggering options

### ISSUE THREAD

**Issue by gafter** [JuliaServices/AutoHashEqualsCached.jl#31]
Rather than have a whole host of different macros for slightly different situations, we should use optional keyword arguments before the type declaration.  That is more extensible and permits us to export only one macro.

Some of the possible options:
- `cached=true` - to compute the hash code at construction time and cache it in a "hidden" field.
- `althashname=MuttsDicts.mutts_hash` - the name of the hash function to be implemented.
- `fields=(x, y)` - define the set of fields that should participate in equality and hash.
- `reference=true` - make the type a reference type, but make all of its fields `const`.  Requires Julia 1.8 or above.
- `nohash=true` - to skip defining a hash code altogether Mutually exclusive with the `althashname` option.
- `noequals=true` - to skip defining `==` altogether.  Mutually exclusive with the `nohash` option.

For example

```julia
@auto_hash_equals althashname=MuttsDicts.mutts_hash reference=true cached=true struct Pair
    x
    y
end
```

**Comment by NHDaly** [comment]
FYI: we've so far more or less been follow https://github.com/invenia/BlueStyle at RAI (though there's been discussion to switch to https://github.com/jrevels/YASGuide), and one of the things that it suggests, which I like, is to mostly avoid `smooshedcase` outside of Base. I think it's a particularly odd decision that Julia made, and that it's fine to leave it like that in Base, but that package code and application code should mostly prefer `snake_case`.

`althashname` triggered my 👀 as something that should probably be `alt_hash_name` 😊

**Comment by NHDaly** [comment]
For the other `no*` ones, i think it could be up to you.. i'd probably put an underscore there too, but i think reasonable people could disagree there :)

-----

This seems like a good idea overall though, yeah!

**Comment by NHDaly** [comment]
Another option could be to have some sub-macros that users put on individual fields which your top-level struct macro could pick up. Like `@nohash` on a specific field or something. I think it's a matter of syntactic preference at that point.
